vpc:
  local:
    subnetIds:
    securityGroupIds:

  dev:
    subnetIds:
      ${ssm:/InternalApi/Vpc/Subnets~split}
    securityGroupIds:
      ${ssm:/InternalApi/Vpc/SecurityGroups~split}

  prod:
    subnetIds:
      ${ssm:/InternalApi/Vpc/Subnets~split}
    securityGroupIds:
      ${ssm:/InternalApi/Vpc/SecurityGroups~split}