image: node:10.16.3
  
pipelines:
  branches:
    master:
      - step:
          name: Test and build
          script:
            - npm i
            - npm run test
            - npm run build
            - rm -rf node_modules
            - npm i --production
          artifacts:
            - dist/**
            - migrations/**
            - config/**
            - node_modules/**

      - step:
          name: Run staging migrations
          script: 
            - echo "TBA"

      - step:
          name: Deploy to staging
          script:
            - npm i serverless -g
            - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            - serverless deploy --stage dev

      - step:
          name: Run production migrations
          trigger: manual
          script: 
            - echo "TBA"

      - step:
          name: Deploy to production
          trigger: manual
          script:
            - npm i serverless -g
            - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            - serverless deploy --stage prod
