image: node:10.16.3
  
pipelines:
  branches: 
    master:
      - step: 
          name: Test and build
          script: 
            - npm i
            - npm run test
            - npm run build
            - rm -rf node_modules
            - npm i --production
          artifacts:
            - dist/**
            - migrations/**
            - config/**
            - node_modules/**
      - step:
          name: Deploy
          script:
            - cp config.yml.dist config.yml
            - echo "\${ssm:/aws/reference/secretsmanager/prod/microservice/config~true}" > ./config.yml
            - npm i serverless -g
            - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            - serverless deploy
