image: node:10.16.3
  
pipelines:
  branches: 
    staging:
      - step: 
          name: Test and build
          script: 
            - npm i
            - npm run test
            - npm run build
            - rm -rf node_modules
      - step:
          name: Deploy
          script:
            - npm i serverless -g
            - serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - serverless deploy
