version: '2'
services:
  serverless_db:
    image: mysql:5.7
    container_name: serverless_db
    command: "--default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0"
    volumes:
      - ./environment/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    network_mode: "bridge"