service: itsjeffro

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  apiGateway: 
    restApiId: 
      'Fn::ImportValue': ApiGateway-${self:provider.stage}-restApiId
    restApiRootResourceId: 
      'Fn::ImportValue': ApiGateway-${self:provider.stage}-rootResourceId
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    JWT_SIGNING_KEY: ${env:JWT_SIGNING_KEY}

package:
  exclude:
    - ./**
    - '!node_modules/**'
    - node_modules/aws-sdk/**
  include:
    - dist/**
    - migrations/**
    - config/**

functions:
  authorizer:
    handler: dist/handlers/authorizer.authorizer
    tags:
      Environment: ${self:provider.stage}
      Name: authorizer-${self:provider.stage}-lambda

  getPosts:
    handler: dist/handlers/posts.getPosts
    tags:
      Environment: ${self:provider.stage}
      Name: getPosts-${self:provider.stage}-lambda
    events:
      - http:
          path: posts
          method: get
          cors: true
          authorizer: authorizer
          private: true

  getPost:
    handler: dist/handlers/posts.getPost
    tags:
      Environment: ${self:provider.stage}
      Name: getPost-${self:provider.stage}-lambda
    events:
      - http:
          path: posts/{uuid}
          method: get
          cors: true
          authorizer: authorizer
          private: true

  createPost:
    handler: dist/handlers/posts.createPost
    tags:
      Environment: ${self:provider.stage}
      Name: createPost-${self:provider.stage}-lambda
    events:
      - http:
          path: posts
          method: post
          cors: true
          authorizer: authorizer
          private: true

  updatePost:
    handler: dist/handlers/posts.updatePost
    tags:
      Environment: ${self:provider.stage}
      Name: updatePost-${self:provider.stage}-lambda
    events:
      - http:
          path: posts/{uuid}
          method: put
          cors: true
          authorizer: authorizer
          private: true

  deletePost:
    handler: dist/handlers/posts.deletePost
    tags:
      Environment: ${self:provider.stage}
      Name: deletePost-${self:provider.stage}-lambda
    events:
      - http:
          path: posts/{uuid}
          method: delete
          cors: true
          authorizer: authorizer
          private: true

  migrationProcess:
    handler: dist/handlers/migrations.process

resources: 
  Resources: 
    PostsTopic: 
      Type: AWS::SNS::Topic 
      Properties: 
        DisplayName: 'Posts Topic' 
        TopicName: PostsTopic