service: itsjeffro

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  apiName: itsjeffro
  usagePlan:
    throttle:
      burstLimit: 5
      rateLimit: 1

functions:
  authorizer:
    handler: dist/authorizer.authorizer

  getPosts:
    handler: dist/posts.getPosts
    events:
      - http:
          path: posts
          method: get
          cors: true
          authorizer: authorizer
          private: true

  getPost:
    handler: dist/posts.getPost
    events:
      - http:
          path: posts/{uuid}
          method: get
          cors: true
          authorizer: authorizer
          private: true

  createPost:
    handler: dist/posts.createPost
    events:
      - http:
          path: posts
          method: post
          cors: true
          authorizer: authorizer
          private: true

  updatePost:
    handler: dist/posts.updatePost
    events:
      - http:
          path: posts/{uuid}
          method: put
          cors: true
          authorizer: authorizer
          private: true

  deletePost:
    handler: dist/posts.deletePost
    events:
      - http:
          path: posts/{uuid}
          method: delete
          cors: true
          authorizer: authorizer
          private: true

  migrationProcess:
    handler: dist/migrations.process

resources: 
  Resources: 
    PostsTopic: 
      Type: AWS::SNS::Topic 
      Properties: 
        DisplayName: 'Posts Topic' 
        TopicName: PostsTopic