service: itsjeffro-migrations

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  environment: ${file(./serverless/config/env.yml):${self:provider.stage}.env}
  vpc: ${file(./serverless/config/vpc.yml):${self:provider.stage}.vpc}

package:
  exclude:
    - ./**
    - '!node_modules/**'
    - node_modules/aws-sdk/**
  include:
    - dist/**
    - migrations/**
    - config/**

custom:
  app:
    version: v1

functions:

  migrationProcess:
    handler: dist/handlers/migrations.process
    reservedConcurrency: 1
    events:
      - sqs:
          batchSize: 1
          arn:
            Fn::GetAtt: 
              - PostsMigrationsQueue
              - Arn

resources:

  Resources:

    # SQS: Failed migrations
    # ======================
    # - Retain failed messages for 14 days (1209600)
    PostsMigrationsDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: posts-${self:provider.stage}-migrations-dlq
        MessageRetentionPeriod: 1209600
    
    # SQS: Migrations
    # ===============
    # - Sends messages to dead letter queue after being recevied once
    PostsMigrationsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: posts-${self:provider.stage}-migrations
        RedrivePolicy:
          maxReceiveCount: 1
          deadLetterTargetArn: 
            Fn::GetAtt: 
              - PostsMigrationsDeadLetterQueue 
              - Arn 
