service: itsjeffro

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  apiName: itsjeffro
  usagePlan:
    throttle:
      burstLimit: 5
      rateLimit: 1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    JWT_SIGNING_KEY: ${env:JWT_SIGNING_KEY}

package:
  exclude:
    - '!node_modules/**'
    - node_modules/aws-sdk/**
    - src/**
    - ./**
  include:
    - dist/**
    - migrations/**
    - config/**

functions:
  authorizer:
    handler: dist/handlers/authorizer.authorizer

  getPosts:
    handler: dist/handlers/posts.getPosts
    events:
      - http:
          path: posts
          method: get
          cors: true
          authorizer: authorizer
          private: true

  getPost:
    handler: dist/handlers/posts.getPost
    events:
      - http:
          path: posts/{uuid}
          method: get
          cors: true
          authorizer: authorizer
          private: true

  createPost:
    handler: dist/handlers/posts.createPost
    events:
      - http:
          path: posts
          method: post
          cors: true
          authorizer: authorizer
          private: true

  updatePost:
    handler: dist/handlers/posts.updatePost
    events:
      - http:
          path: posts/{uuid}
          method: put
          cors: true
          authorizer: authorizer
          private: true

  deletePost:
    handler: dist/handlers/posts.deletePost
    events:
      - http:
          path: posts/{uuid}
          method: delete
          cors: true
          authorizer: authorizer
          private: true

  migrationProcess:
    handler: dist/handlers/migrations.process

resources: 
  Resources: 
    PostsTopic: 
      Type: AWS::SNS::Topic 
      Properties: 
        DisplayName: 'Posts Topic' 
        TopicName: PostsTopic