service: itsjeffro

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}
  apiGateway: 
    restApiId: 
      'Fn::ImportValue': ApiGateway-${self:provider.stage}-restApiId
    restApiRootResourceId: 
      'Fn::ImportValue': ApiGateway-${self:provider.stage}-rootResourceId
  environment:
    DB_HOST: ${self:custom.app.config.database.host}
    DB_USER: ${self:custom.app.config.database.user}
    DB_PASSWORD: ${self:custom.app.config.database.password}
    DB_PORT: ${self:custom.app.config.database.port}
    DB_DATABASE: ${self:custom.app.config.database.database}
  vpc:
    securityGroupIds: ${self:custom.app.config.securityGroupIds}
    subnetIds: ${self:custom.app.config.subnetIds}

package:
  exclude:
    - ./**
    - '!node_modules/**'
    - node_modules/aws-sdk/**
  include:
    - dist/**
    - migrations/**
    - config/**

custom:
  app:
    config: ${file(./config.yml):config}
  apiGateway:
    authorizerId:
      Fn:ImportValue: ApiGateway-${self:provider.stage}-authorizer

functions:
  getPosts:
    handler: dist/handlers/posts.getPosts
    events:
      - http:
          path: posts
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:api-gateway-dev.apiGatewayRestApiAuthorizer}

  getPost:
    handler: dist/handlers/posts.getPost
    events:
      - http:
          path: posts/{uuid}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:api-gateway-dev.apiGatewayRestApiAuthorizer}

  createPost:
    handler: dist/handlers/posts.createPost
    events:
      - http:
          path: posts
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:api-gateway-dev.apiGatewayRestApiAuthorizer}

  updatePost:
    handler: dist/handlers/posts.updatePost
    events:
      - http:
          path: posts/{uuid}
          method: put
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:api-gateway-dev.apiGatewayRestApiAuthorizer}

  deletePost:
    handler: dist/handlers/posts.deletePost
    events:
      - http:
          path: posts/{uuid}
          method: delete
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: ${cf:api-gateway-dev.apiGatewayRestApiAuthorizer}

  migrationProcess:
    handler: dist/handlers/migrations.process

resources:
  Resources:
    PostsTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: 'Posts Topic'
        TopicName: PostsTopic-${self:provider.stage}
