service: itsjeffro

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  apiName: itsjeffro

functions:
  getPosts:
    handler: handler.getPosts
    events:
      - http:
          path: posts
          method: get
          cors: true
          private: true

  getPost:
    handler: handler.getPost
    events:
      - http:
          path: posts/{uuid}
          method: get
          cors: true
          private: true

  createPost:
    handler: handler.createPost
    events:
      - http:
          path: posts
          method: post
          cors: true
          private: true

  updatePost:
    handler: handler.updatePost
    events:
      - http:
          path: posts/{uuid}
          method: put
          cors: true
          private: true

  deletePost:
    handler: handler.deletePost
    events:
      - http:
          path: posts/{uuid}
          method: delete
          cors: true
          private: true