service: itsjeffro

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  apiName: itsjeffro
  usagePlan:
    throttle:
      burstLimit: 5
      rateLimit: 1

functions:
  authorizer:
    handler: handlers/authorizer.authorizer

  getPosts:
    handler: handler.getPosts
    events:
      - http:
          path: posts
          method: get
          cors: true
          authorizer: authorizer
          private: true

  getPost:
    handler: handler.getPost
    events:
      - http:
          path: posts/{uuid}
          method: get
          cors: true
          authorizer: authorizer
          private: true

  createPost:
    handler: handler.createPost
    events:
      - http:
          path: posts
          method: post
          cors: true
          authorizer: authorizer
          private: true

  updatePost:
    handler: handler.updatePost
    events:
      - http:
          path: posts/{uuid}
          method: put
          cors: true
          authorizer: authorizer
          private: true

  deletePost:
    handler: handler.deletePost
    events:
      - http:
          path: posts/{uuid}
          method: delete
          cors: true
          authorizer: authorizer
          private: true