name: Serverless Demo
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Use Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: Test and build
        run: |
          npm i
          npm test
          npm run build
          rm -rf node_modules
          npm i --production
      - name: Serverless deploy
        run: |
          npm i serverless -g
          serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          serverless deploy
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
